// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Money(_) {
  var make = function (a) {
    return a;
  };
  var get = function (a) {
    return a;
  };
  var $plus = function (a, b) {
    return a + b | 0;
  };
  return {
          make: make,
          get: get,
          $plus: $plus
        };
}

var BRLConfig = {
  prefix: "BRL"
};

var USDConfig = {
  prefix: "USD"
};

function make(a) {
  return a + "shauhsas";
}

var Encrypt = {
  make: make
};

function make$1(a) {
  return a;
}

function get(a) {
  return a;
}

function $plus(a, b) {
  return a + b | 0;
}

var BRL = {
  make: make$1,
  get: get,
  $plus: $plus
};

function make$2(a) {
  return a;
}

function get$1(a) {
  return a;
}

function $plus$1(a, b) {
  return a + b | 0;
}

var USD = {
  make: make$2,
  get: get$1,
  $plus: $plus$1
};

var balanceBRL = 12;

var balanceUSD = 10;

var finalBRL = balanceBRL + 10 | 0;

function getHome(param) {
  return {
          NAME: "home",
          VAL: React.createElement("p", undefined, "Hellooo")
        };
}

function getAbout(param) {
  return {
          NAME: "home",
          VAL: React.createElement("p", undefined, "About")
        };
}

function render(state) {
  return state.VAL;
}

function App(Props) {
  var match = React.useState(function () {
        return getHome(undefined);
      });
  var setState = match[1];
  return React.createElement("div", undefined, React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return getHome(undefined);
                                  }));
                    })
                }, "Home"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setState, (function (param) {
                                    return getAbout(undefined);
                                  }));
                    })
                }, "Abbout"), match[0].VAL);
}

var password = "passwordshauhsas";

var backToInt = finalBRL;

var make$3 = App;

exports.Money = Money;
exports.BRLConfig = BRLConfig;
exports.USDConfig = USDConfig;
exports.Encrypt = Encrypt;
exports.password = password;
exports.BRL = BRL;
exports.USD = USD;
exports.balanceBRL = balanceBRL;
exports.balanceUSD = balanceUSD;
exports.finalBRL = finalBRL;
exports.backToInt = backToInt;
exports.getHome = getHome;
exports.getAbout = getAbout;
exports.render = render;
exports.make = make$3;
/* react Not a pure module */
